Added the redux setup with redux-toolkit
Revature-Capstone-1350/e-commerce-frontend pull request #4
Opened 2022-07-15 20:20 UTC by treymeetsworld

Potential problem: while installing redux dependencies i had to use `--legacy-peer-deps` flag at the end of npm install to get the dependencies to install correctly. This is a problem with a new feature for npm [stack overflow problem discussion](https://stackoverflow.com/questions/64936044/fix-the-upstream-dependency-conflict-installing-npm-packages).
An easier fix instead of adding the flag every time is running this command `npm config set legacy-peer-deps true` .

2022-07-15 20:37 UTC, FDDTheLucario requested changes
- add some comments to clarify what the code does

2022-07-15 20:52 UTC, treymeetsworld commented
> * add some comments to clarify what the code does

working on it

2022-07-18 14:13 UTC, FDDTheLucario requested changes
- require semicolons.

2022-07-19 14:12 UTC, FDDTheLucario submitted a review, later dismissed

2022-07-20 16:49 UTC, SosaTheHustler approved these changes

2022-07-20 16:51 UTC, merged